#!/usr/bin/env bash

CONFIG_DIR=~/.config/pine-lang
TMP_DIR=/tmp/.pine-lang

cli_log() {
  script_name=${0##*/}
  timestamp=$(date -u +"%Y-%m-%d %H:%M:%S")
  echo " :: $timestamp :: [$script_name] ::  $1"
}
