#!/usr/bin/env bash
set -e
export WORKDIR=$(cd "$(dirname "$(realpath "$0")")" && pwd)
. "$WORKDIR/common"

cli_help() {
  cli_name=${0##*/}
  echo "
$cli_name
Pine CLI
Version: $(cat $WORKDIR/VERSION)
https://github.com/pine-lang/pine-cli

Usage: $cli_name [command]

Commands:
  serve     Run the pine server and the web app
  repl      Run the clojure repl for development. Connect to it using emacs `cider-connect-clj`
  config    See the configuration i.e. database connections etc.
  *         Help
"
  exit 1
}

# cli_log "Reading configuration"
# [ ! -f "$CONFIG_DIR/config" ] \
#   && echo "ERROR: No $CONFIG_DIR/config file found. " \
#   && echo "Run install script." \
#   && exit 1

# export $(cat "$CONFIG_DIR/config" | xargs)

case "$1" in
  config)
    "$WORKDIR/commands/config"
     ;;
  serve)
    "$WORKDIR/commands/serve" | tee -ia "$WORKDIR/logs/serve.log"
    ;;
  repl)
    "$WORKDIR/commands/repl" | tee -ia "$WORKDIR/logs/repl.log"
    ;;
  *)
    cli_help
    ;;
esac
